config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :devices
  namespace :attachment do
    resources :videos
    resources :photos
  end
  resources :attachments
  resources :photos
  resources :magazines do
    resources :authors
    resources :issues do
      resources :articles
    end
  end

  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'

  namespace :madmin do
    resources :impersonates do
      post :impersonate, on: :member
      post :stop_impersonating, on: :collection
    end
  end
end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/issue.rb
class Issue < ApplicationRecord
  belongs_to :magazine
  has_rich_text :cover
  has_many :articles
  has_many :authors, through: :articles
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: %i[ show edit update destroy ]

  # GET /issues or /issues.json
  def index
    @issues = Issue.all
  end

  # GET /issues/1 or /issues/1.json
  def show
  end

  # GET /issues/new
  def new
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues or /issues.json
  def create
    @issue = Issue.new(issue_params)

    respond_to do |format|
      if @issue.save
        format.html { redirect_to issue_url(@issue), notice: "Issue was successfully created." }
        format.json { render :show, status: :created, location: @issue }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1 or /issues/1.json
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to issue_url(@issue), notice: "Issue was successfully updated." }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1 or /issues/1.json
  def destroy
    @issue.destroy!

    respond_to do |format|
      format.html { redirect_to issues_url, notice: "Issue was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def issue_params
      params.require(:issue).permit(:publish_date, :magazine_id)
    end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.slim
= simple_form_for(@issue) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :publish_date
    = f.association :magazine

  .form-actions
    = f.button :submit

app/views/issues/_issue.html.slim
div id="#{dom_id issue}"
  p
    strong Publish date:
    =< issue.publish_date
  p
    strong Magazine:
    =< issue.magazine_id

app/views/issues/edit.html.slim
h1 Editing issue

== render "form", issue: @issue

br

div
  => link_to "Show this issue", @issue
  '|
  =< link_to "Back to issues", issues_path

app/views/issues/index.html.slim
p style="color: green" = notice

h1 Issues

#issues
  - @issues.each do |issue|
    == render issue
    p
      = link_to "Show this issue", issue

= link_to "New issue", new_issue_path

app/views/issues/new.html.slim
h1 New issue

== render "form", issue: @issue

br

div
  = link_to "Back to issues", issues_path

app/views/issues/show.html.slim
p style="color: green" = notice

== render @issue

div
  => link_to "Edit this issue", edit_issue_path(@issue)
  '|
  =< link_to "Back to issues", issues_path

  = button_to "Destroy this issue", @issue, method: :delete