config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :devices
  namespace :attachment do
    resources :videos
    resources :photos
  end
  resources :attachments
  resources :photos
  resources :magazines do
    resources :authors
    resources :issues do
      resources :articles
    end
  end

  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'

  namespace :madmin do
    resources :impersonates do
      post :impersonate, on: :member
      post :stop_impersonating, on: :collection
    end
  end
end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/magazine.rb
class Magazine < ApplicationRecord
  has_rich_text :description
  has_many :authors
  has_many :issues
end

app/controllers/magazines_controller.rb
class MagazinesController < ApplicationController
  before_action :set_magazine, only: %i[ show edit update destroy ]

  # GET /magazines or /magazines.json
  def index
    @magazines = Magazine.all
  end

  # GET /magazines/1 or /magazines/1.json
  def show
  end

  # GET /magazines/new
  def new
    @magazine = Magazine.new
  end

  # GET /magazines/1/edit
  def edit
  end

  # POST /magazines or /magazines.json
  def create
    @magazine = Magazine.new(magazine_params)

    respond_to do |format|
      if @magazine.save
        format.html { redirect_to magazine_url(@magazine), notice: "Magazine was successfully created." }
        format.json { render :show, status: :created, location: @magazine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @magazine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /magazines/1 or /magazines/1.json
  def update
    respond_to do |format|
      if @magazine.update(magazine_params)
        format.html { redirect_to magazine_url(@magazine), notice: "Magazine was successfully updated." }
        format.json { render :show, status: :ok, location: @magazine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @magazine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /magazines/1 or /magazines/1.json
  def destroy
    @magazine.destroy!

    respond_to do |format|
      format.html { redirect_to magazines_url, notice: "Magazine was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_magazine
      @magazine = Magazine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def magazine_params
      params.require(:magazine).permit(:name, :description)
    end
end

app/helpers/magazines_helper.rb
module MagazinesHelper
end

app/views/magazines/_form.html.slim
= simple_form_for(@magazine) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name, input_html: {class: 'form-control-lg'}
    = f.input :description, as: :rich_text_area, label: 'Content', placeholder: 'Text goes here' 

  .form-actions
    = f.button :submit, class: "btn btn-primary mb-2"

app/views/magazines/_magazine.html.slim
div id="#{dom_id magazine}"
  p
    strong Name:
    =< magazine.name
  p
    strong Description:
    =< magazine.description

app/views/magazines/edit.html.slim
h1 Editing magazine

== render "form", magazine: @magazine

br

div
  => link_to "Show this magazine", @magazine
  '|
  =< link_to "Back to magazines", magazines_path

app/views/magazines/index.html.slim
p style="color: green" = notice

h1 Magazines

#magazines
  - @magazines.each do |magazine|
    == render magazine
    p
      = link_to "Show this magazine", magazine

= link_to "New magazine", new_magazine_path

app/views/magazines/new.html.slim
h1 New magazine

== render "form", magazine: @magazine

br

div
  = link_to "Back to magazines", magazines_path

app/views/magazines/show.html.slim
p style="color: green" = notice

== render @magazine

div
  => link_to "Edit this magazine", edit_magazine_path(@magazine)
  '|
  =< link_to "Back to magazines", magazines_path

  = button_to "Destroy this magazine", @magazine, method: :delete